version: "3.7"

services:

  gogs:
    image: thecodecamp/gogs:0.12.3
    ports:
      - "3000:3000"
    networks:
      - cicd-network

  jenkins:
    image: thecodecamp/jenkins:2.327-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd-network

  tomcat:
    image: tomcat:8.0
    ports:
      - "8888:8080"
    volumes:
      - ${PWD}/tomcat-users/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    networks:
      - cicd-network

networks:
  cicd-network:
    name: cicd-network
